name: Compress and Upload to S3

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y awscli

    - name: Create compressed directory
      run: mkdir -p compressed

    - name: Compress PHP files
      run: |
        cd dynamic  # PHP 파일이 있는 디렉토리로 이동
        zip -r ./dynamic.zip ./*.php  # 압축 파일 생성 후 압축 파일을 compressed 폴더로 이동


    - name: Compress all files
      run: |
        cd dynamic  # PHP 파일이 있는 디렉토리로 이동
        zip -r ../compressed/dynamic_files.zip ./*  # 압축 파일 생성 후 압축 파일을 compressed 폴더로 이동

    - name: Compress HTML files
      run: |
        cd static  # HTML 파일이 있는 디렉토리로 이동
        zip -r ../compressed/static_files.zip *  # 압축 파일 생성 후 압축 파일을 compressed 폴더로 이동

    - name: Upload PHP files to S3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
      run: |
        aws s3 cp compressed/dynamic_files.zip s3://kms-deploy-bucket/dynamic/dynamic_files.zip

    - name: Upload HTML files to S3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
      run: |
        aws s3 cp compressed/static_files.zip s3://kms-deploy-bucket/static/static_files.zip