name: Compress and Upload to S3

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Compress PHP files
      run: |
        mkdir -p compressed
        zip -r compressed/dynamic_files.zip *.php

    - name: Compress HTML files
      run: |
        zip -r compressed/static_files.zip *.html

    - name: Upload PHP files to S3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
      run: |
        aws s3 cp compressed/php_files.zip s3://kms-deploy-bucket/dynamic/dynamic_files.zip

    - name: Upload HTML files to S3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
      run: |
        aws s3 cp compressed/html_files.zip s3://kms-deploy-bucket/static/static_files.zip
